version: "3.8"

services:
  bot_postgres:
    container_name: bot_postgres
    image: postgres:15
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Aa102938aA
      POSTGRES_DB: linkedin_jobs_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
  bot_redis:
    container_name: bot_redis
    image: redis:latest
    ports:
      - "7917:7917"
    restart: always
    environment:
      REDIS_PASSWORD: Aa102938aA
  bar_mongodb:
    container_name: bar_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
  bot_backend:
    build: ./
    restart: always
    container_name: bot_backend
    depends_on:
      - "bot_postgres"
      - "bot_redis"
      - "bar_mongodb"
    ports:
      - "8888:8080"
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bot_postgres:5432/linkedin_jobs_bot
      - SPRING_DATA_MONGODB_URI=mongodb://bar_mongodb:27017/jobs_db
      - SPRING_DATA_REDIS_HOST=bot_redis
      - SPRING_DATA_REDIS_PASSWORD=Aa102938aA
      - SPRING_DATASOURCE_PASSWORD=Aa102938aA
      - BOT_NAME=
      - BOT_TOKEN=
      - BOT_COOKIE=
      - BOT_CSRF_TOKEN=
volumes:
  postgres-data:
