name: linkedin_jobs_bot
services:
  bot_main:
    build: ./linkedin-jobs-bot-main
    restart: always
    container_name: bot_main
    network_mode: host
    working_dir: /app
    environment:
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/linkedin_jobs_bot
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_DATA_MONGODB_HOST=localhost
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=jobs_db
      - SPRING_DATA_MONGODB_PASSWORD=${PASSWORD}
      - SPRING_DATA_MONGODB_USERNAME=${USER}
      - SPRING_DATA_REDIS_HOST=localhost
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - SPRING_KAFKA_BOOTSTRAPSERVERS=localhost:29093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";


  #      - SPRING_KAFKA_SSL_TRUSTSTORELOCATION=file:/app/build/resources/main/client-certs/kafka.producer.truststore.jks
#      - SPRING_KAFKA_SSL_TRUSTSTOREPASSWORD=${PASSWORD}
#      - SPRING_KAFKA_SSL_KEYSTORELOCATION=file:/app/build/resources/main/client-certs/kafka.producer.keystore.jks
#      - SPRING_KAFKA_SSL_KEYSTOREPASSWORD=${PASSWORD}
#      - SPRING_KAFKA_SSL_KEYPASSWORD=${PASSWORD}
#      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
#      - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=PLAIN
#      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_ADMIN_USERNAME}" password="${KAFKA_ADMIN_PASSWORD}";

  bot_scanner_one:
    build: ./job-scanner
    restart: always
    container_name: bot_scanner_one
    depends_on:
      - bot_main
    network_mode: host
    working_dir: /app
    environment:
      - SERVER_PORT=8091
      - SPRING_DATA_MONGODB_HOST=localhost
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=jobs_db
      - SPRING_DATA_MONGODB_PASSWORD=${PASSWORD}
      - SPRING_DATA_MONGODB_USERNAME=${USER}
      - BOT_USERNAME=${BOT_USERNAME_ONE}
      - BOT_PASSWORD=${BOT_PASSWORD_ONE}
      - BOT_COOKIE=${BOT_COOKIE_ONE}
      - BOT_CSRF_TOKEN=${BOT_CSRF_TOKEN_ONE}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:29093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";

#      - SPRING_KAFKA_SSL_TRUST_STORE_LOCATION=file:/app/build/resources/main/client-certs/kafka.consumer.truststore.jks
#      - SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD=${PASSWORD}
#      - SPRING_KAFKA_SSL_KEY_STORE_LOCATION=file:/app/build/resources/main/client-certs/kafka.consumer.keystore.jks
#      - SPRING_KAFKA_SSL_KEY_STORE_PASSWORD=${PASSWORD}
#      - SPRING_KAFKA_SSL_KEY_PASSWORD=${PASSWORD}

#      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
#      - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=PLAIN
#      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_ADMIN_USERNAME}" password="${KAFKA_ADMIN_PASSWORD}";

  bot_scanner_two:
    build: ./job-scanner
    restart: always
    container_name: bot_scanner_two
    depends_on:
      - bot_main
    network_mode: host
    working_dir: /app
    environment:
      - SERVER_PORT=8092
      - SPRING_DATA_MONGODB_HOST=localhost
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=jobs_db
      - SPRING_DATA_MONGODB_PASSWORD=${PASSWORD}
      - SPRING_DATA_MONGODB_USERNAME=${USER}
      - BOT_USERNAME=${BOT_USERNAME_TWO}
      - BOT_PASSWORD=${BOT_PASSWORD_TWO}
      - BOT_COOKIE=${BOT_COOKIE_TWO}
      - BOT_CSRF_TOKEN=${BOT_CSRF_TOKEN_TWO}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=localhost:29093
      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${PASSWORD}";


#      - SPRING_KAFKA_SSL_TRUST_STORE_LOCATION=file:/app/build/resources/main/client-certs/kafka.consumer.truststore.jks
#      - SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD=${PASSWORD}
#      - SPRING_KAFKA_SSL_KEY_STORE_LOCATION=file:/app/build/resources/main/client-certs/kafka.consumer.keystore.jks
#      - SPRING_KAFKA_SSL_KEY_STORE_PASSWORD=${PASSWORD}
#      - SPRING_KAFKA_SSL_KEY_PASSWORD=${PASSWORD}
#
#      - SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
#      - SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=PLAIN
#      - SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_ADMIN_USERNAME}" password="${KAFKA_ADMIN_PASSWORD}";