version: "3.8"

services:
  bot_postgres:
    container_name: bot_postgres
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkedin_jobs_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
  bot_redis:
    container_name: bot_redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  bar_mongodb:
    container_name: bar_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
  bot_backend:
    build: ./
    restart: always
    container_name: bot_backend
    depends_on:
      - "bot_postgres"
      - "bot_redis"
      - "bar_mongodb"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bot_postgres:5432/linkedin_jobs_bot
      - SPRING_DATA_MONGODB_URI=mongodb://bar_mongodb:27017/jobs_db
      - SPRING_DATA_REDIS_HOST=bot_redis
volumes:
  postgres-data:
