version: "3.8"

services:
  bot_postgres:
    container_name: bot_postgres
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: linkedin_jobs_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
  bot_redis:
    container_name: bot_redis
    image: redis:latest
    env_file:
      - ../.env
    ports:
      - "7917:7917"
    environment:
      REDIS_PASSWORD: ${PASSWORD}
    restart: always
  bot_mongodb:
    container_name: bot_mongodb
    image: mongodb/mongodb-community-server:latest
    command: mongod --port 27018
    env_file:
      - ../.env
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    restart: always
  bot_backend:
    build: ./
    restart: always
    env_file:
      - ../.env
    container_name: bot_backend
    depends_on:
      - "bot_postgres"
      - "bot_redis"
      - "bot_mongodb"
    ports:
      - "8888:8080"
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bot_postgres:5432/linkedin_jobs_bot
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
      - SPRING_DATA_MONGODB_HOST=bot_mongodb
      - SPRING_DATA_MONGODB_PORT=27018
      - SPRING_DATA_MONGODB_DATABASE=jobs_db
      - SPRING_DATA_MONGODB_PASSWORD=${PASSWORD}
      - SPRING_DATA_MONGODB_USERNAME=${USERNAME}
      - SPRING_DATA_REDIS_HOST=bot_redis
      - SPRING_DATA_REDIS_PASSWORD=${PASSWORD}
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_COOKIE=${BOT_COOKIE}
      - BOT_CSRF_TOKEN=${BOT_CSRF_TOKEN}
volumes:
  postgres-data: